---
galaxy_info:
  role_name: wsl
  author: ldonnez
  description: WSL specific configuration
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: dotfiles
