- name: Install qemu-kvm libvirt-daemon-system, libvirt-clients bridg-utils virt-manager
  become: true
  ansible.builtin.apt:
    name:
      [
        "qemu-kvm",
        "libvirt-daemon-system",
        "libvirt-clients",
        "bridge-utils",
        "virt-manager",
      ]
    state: present
  tags:
    - install

- name: Ensure current user is added to groups libvirt & kvm to start VM's without root
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt,kvm
    append: true
  tags:
    - install

- name: Enable service libvirtd and ensure it is not masked
  become: true
  ansible.builtin.systemd_service:
    name: libvirtd
    enabled: true
    masked: false
  tags:
    - install

- name: Make sure libvirtd unit is running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: libvirtd
  tags:
    - install
