- name: Install synology-drive via homebrew cask
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    name: synology-drive
    state: present
  tags:
    - install

- name: Update synology-drive via homebrew cask
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    update_homebrew: true
    name: synology-drive
    greedy: true
    state: upgraded
  tags:
    - update
