- name: Check if private directory exists
  ansible.builtin.stat:
    path: "{{ private_dotfiles_path }}"
  register: secrets_private_directory
  tags:
    - install

- name: Ensure private directory
  when: not secrets_private_directory.stat.exists
  tags:
    - install

  block:
    - name: "Synchronization {{ private_dotfiles_path }}"
      ansible.posix.synchronize:
        src: "{{ private_dotfiles_source }}/"
        dest: "{{ private_dotfiles_path }}/"
        recursive: true
        delete: true
        checksum: true
      when: private_dotfiles_source is defined and private_dotfiles_path is defined
      tags:
        - install

- name: Symlink secrets
  when: private_dotfiles_source is defined and private_dotfiles_path is defined
  tags:
    - install

  block:
    - name: Symlink .secrets
      ansible.builtin.file:
        src: "{{ private_dotfiles_path }}/.secrets"
        dest: "{{ ansible_env.HOME }}/.secrets"
        state: link

    - name: Ensure access rights
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.secrets"
        mode: "0700"
      become: true
      become_user: root
