---
- name: Check if .secrets already exists
  ansible.builtin.stat:
    path: "{{ secrets_directory }}"
  register: secrets_dir
  tags:
    - install

- name: Check GitHub CLI authentication
  ansible.builtin.command: gh auth status
  register: secrets_gh_status
  failed_when: false
  changed_when: false
  when: not secrets_dir.stat.exists
  tags:
    - install

- name: GitHub authentication required
  ansible.builtin.pause:
    prompt: |
      GitHub login required

      Run the following command in another terminal:

      gh auth login

      If you are on a headless server, you can switch to another terminal session using Ctrl+Alt+F2.

      For headless environments, run:

      BROWSER=false gh auth login

      Note that the process may take a few moments to complete while you approve the login in your browser or device.

      Then press ENTER here to continue.
  when: not secrets_dir.stat.exists and secrets_gh_status.rc != 0
  tags:
    - install

- name: Add gh as git credential helper
  ansible.builtin.command: gh auth setup-git
  failed_when: false
  changed_when: false
  when: not secrets_dir.stat.exists
  tags:
    - install

- name: Clone secrets repo
  ansible.builtin.git:
    repo: "{{ secrets_repository }}"
    dest: "{{ secrets_directory }}"
    version: main
  when: not secrets_dir.stat.exists
  tags:
    - install
