---
- name: Install latest firefox with apt
  when: ansible_facts.os_family == "Debian"
  become: true
  tags:
    - install
  block:
    - name: Install python3-debian (required by deb822_repository)
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Add mozilla to sources list
      ansible.builtin.deb822_repository:
        name: mozilla
        types: deb
        uris: https://packages.mozilla.org/apt
        suites: mozilla
        components: main
        signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
        state: present

    - name: Configure APT to prioritize packages from the Mozilla repository
      ansible.builtin.copy:
        dest: "/etc/apt/preferences.d/mozilla"
        content: |
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
        mode: "0644"

    - name: Install firefox with apt
      ansible.builtin.apt:
        name: firefox
        update_cache: true

    - name: Remove firefox-esr
      ansible.builtin.apt:
        name: firefox-esr
        state: absent
