---
- name: Backup to SynologyDrive folder
  hosts: localhost
  connection: local

  vars:
    directories_to_synchronize:
      - name: "dotfiles"
        src: "{{ansible_facts.user_dir}}/dotfiles"
        dest: "{{ansible_facts.user_dir}}/SynologyDrive"
        delete: true

      - name: "config"
        src: "{{ansible_facts.user_dir}}/config"
        dest: "{{ansible_facts.user_dir}}/SynologyDrive"
        delete: true

      - name: "notes"
        src: "{{ansible_facts.user_dir}}/notes"
        dest: "{{ansible_facts.user_dir}}/SynologyDrive"
        delete: true

      - name: "projects"
        src: "{{ansible_facts.user_dir}}/projects/"
        dest: "{{ansible_facts.user_dir}}/SynologyDrive/projects"
        delete: false

  tasks:
    - name: Synchronize
      ansible.builtin.import_role:
        name: synchronize
