---
- name: Setup WSL Ubuntu 22.04
  hosts: localhost
  connection: local

  vars:
    dotfiles_repo: "https://github.com/ldonnez/dotfiles.git"
    dotfiles_directory_path: "{{ ansible_env.HOME }}/dotfiles"

    install_packages: true
    install_dotfiles: true

    configure_wsl: true
    configure_git: true
    configure_zsh: true
    configure_asdf: false
    configure_mise: true
    configure_golang: true
    configure_npm: true
    configure_pip: true
    configure_yarn: true
    configure_rust: true
    configure_haskell: true
    configure_fzf: true
    configure_vim: true
    configure_lsp: true
    configure_terraform: true
    configure_neovim: true
    configure_vifm: true
    configure_bat: true
    configure_tmux: true
    configure_ag: true
    configure_fd: true
    configure_rg: true
    configure_azure_cli: true

    packages:
      - coreutils
      - build-essential
      - htop
      - btop
      - imagemagick
      - jq
      - watchman
      - luarocks
      - tree
      - ninja-build
      - python3-venv
      - clang

    pip_packages:
      - ansible-lint

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: packages
      when: install_packages
      tags:
        - packages

    - name: Configure wsl
      ansible.builtin.import_role:
        name: wsl
      when: configure_wsl
      tags:
        - wsl

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      when: install_dotfiles
      tags:
        - dotfiles

    - name: Configure git
      ansible.builtin.import_role:
        name: git
      when: configure_git
      tags:
        - git

    - name: Configure zsh
      ansible.builtin.import_role:
        name: zsh
      when: configure_zsh
      tags:
        - zsh

    - name: Configure asdf
      ansible.builtin.import_role:
        name: asdf
      when: configure_asdf
      tags:
        - asdf

    - name: Configure mise
      ansible.builtin.import_role:
        name: mise
      when: configure_mise
      tags:
        - mise

    - name: Configure golang
      ansible.builtin.import_role:
        name: golang
      when: configure_golang
      tags:
        - golang

    - name: Configure npm
      ansible.builtin.import_role:
        name: npm
      when: configure_npm
      tags:
        - npm

    - name: Configure pip
      ansible.builtin.import_role:
        name: pip
      when: configure_pip
      tags:
        - pip

    - name: Configure yarn
      ansible.builtin.import_role:
        name: yarn
      when: configure_yarn
      tags:
        - yarn

    - name: Configure rust
      ansible.builtin.import_role:
        name: rust
      when: configure_rust
      tags:
        - rust

    - name: Configure haskell
      ansible.builtin.import_role:
        name: haskell
      when: configure_haskell
      tags:
        - haskell

    - name: Configure fzf
      ansible.builtin.import_role:
        name: fzf
      when: configure_fzf
      tags:
        - fzf

    - name: Configure vifm
      ansible.builtin.import_role:
        name: vifm
      when: configure_vifm
      tags:
        - vifm

    - name: Configure vim
      ansible.builtin.import_role:
        name: vim
      when: configure_vim
      tags:
        - vim

    - name: Configure fd
      ansible.builtin.import_role:
        name: fd
      when: configure_fd
      tags:
        - fd

    - name: Configure rg
      ansible.builtin.import_role:
        name: rg
      when: configure_rg
      tags:
        - rg

    - name: Configure azure cli
      ansible.builtin.import_role:
        name: azure_cli
      when: configure_azure_cli
      tags:
        - azure_cli

    - name: Configure lsp's
      ansible.builtin.import_role:
        name: lsp
      when: configure_lsp
      tags:
        - lsp

    - name: Configure terraform
      ansible.builtin.import_role:
        name: terraform
      when: configure_terraform
      tags:
        - terraform

    - name: Configure neovim
      ansible.builtin.import_role:
        name: neovim
      when: configure_neovim
      tags:
        - neovim

    - name: Configure bat
      ansible.builtin.import_role:
        name: bat
      when: configure_bat
      tags:
        - bat

    - name: Configure ag
      ansible.builtin.import_role:
        name: ag
      when: configure_ag
      tags:
        - ag

    - name: Configure tmux
      ansible.builtin.import_role:
        name: tmux
      when: configure_tmux
      tags:
        - tmux

  environment:
    PATH: "{{ ansible_env.HOME}}/.local/share/mise/shims:{{ansible_env.HOME}}/.local/bin:{{ ansible_env.HOME }}/.npm/bin:{{ ansible_env.HOME}}/.cargo/bin:{{ ansible_env.HOME}}/.ghcup/bin:/usr/local/go/bin:/usr/bin:/usr/sbin:/sbin:/usr/lib/wsl/lib"
