---
- name: Setup Debian 13
  hosts: localhost
  connection: local

  vars:
    dotfiles_repo: "https://github.com/ldonnez/dotfiles.git"
    dotfiles_directory_path: "{{ ansible_facts.user_dir }}/dotfiles"
    private_dotfiles_path: "{{ ansible_facts.user_dir }}/private"
    private_dotfiles_source: "{{ ansible_facts.user_dir }}/SynologyDrive/private"

    install_packages: true
    install_dotfiles: true
    install_nvidia: true
    install_steam: true
    install_docker_desktop: true
    install_fonts: true

    configure_git: true
    configure_zsh: true
    configure_asdf: false
    configure_mise: true
    configure_golang: true
    configure_npm: true
    configure_pip: true
    configure_rust: true
    configure_haskell: true
    configure_fzf: true
    configure_kitty: true
    configure_vim: true
    configure_lsp: true
    configure_neovim: true
    configure_vifm: true
    configure_bat: true
    configure_tmux: true
    configure_ag: true
    configure_fd: true
    configure_rg: true
    configure_memo: true
    configure_libpq: true
    configure_secrets: true
    configure_gnupg: true
    configure_ssh: true
    configure_neomutt: true
    configure_calibre: true
    configure_mbsync_with_cron: false
    configure_fonts: true
    configure_aws: true
    configure_azure_cli: true
    configure_terraform: true
    configure_firefox: true
    configure_discord: true
    configure_spotify: true
    configure_rofi: true
    configure_i3: true
    configure_virt_manager: true
    configure_systemd_resolved: true
    configure_flatpak: true
    configure_synology_drive: true

    packages:
      - coreutils
      - build-essential
      - htop
      - btop
      - imagemagick
      - jq
      - watchman
      - luarocks
      - tree
      - ninja-build
      - python3-venv
      - clang
      - rsync
      - groff
      - vlc
      - thunderbird
      - galculator
      - gparted # Simple program for configuring disk partitioning. Run with root priveleges - sudo gparted.
      - piper # GTK application to configure mouses
      - flameshot # Powerful yet simple-to-use screenshot software
      - zathura # Minimalistic pdf viewer with vim keybindings
      - libreoffice # Full-featured office suite (word, excel, etc...)

    flatpak_apps:
      - com.github.tchx84.Flatseal # Flatseal is a graphical utility to review and modify permissions from your Flatpak applications.
      - com.bitwarden.desktop
      - com.synology.SynologyDrive
      - org.signal.Signal
      - com.slack.Slack
      - com.github.Matoking.protontricks # Run Winetricks commands for Steam Play/Proton games among other common Wine features, such as launching external Windows executables.
      - com.plexamp.Plexamp
      - org.telegram.desktop

    cargo_packages:
      - yazi-fm
      - yazi-cli

    pip_packages:
      - ansible-lint

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: packages
      when: install_packages
      tags:
        - packages

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      when: install_dotfiles
      tags:
        - dotfiles

    - name: Install nvidia
      ansible.builtin.import_role:
        name: nvidia
      when: install_nvidia
      tags:
        - nvidia

    - name: Install steam
      ansible.builtin.import_role:
        name: steam
      when: install_steam
      tags:
        - steam

    - name: Install docker desktop
      ansible.builtin.import_role:
        name: docker_desktop
      when: install_docker_desktop
      tags:
        - docker_desktop

    - name: Configure git
      ansible.builtin.import_role:
        name: git
      when: configure_git
      tags:
        - git

    - name: Configure zsh
      ansible.builtin.import_role:
        name: zsh
      when: configure_zsh
      tags:
        - zsh

    - name: Configure asdf
      ansible.builtin.import_role:
        name: asdf
      when: configure_asdf
      tags:
        - asdf

    - name: Configure mise
      ansible.builtin.import_role:
        name: mise
      when: configure_mise
      tags:
        - mise

    - name: Configure golang
      ansible.builtin.import_role:
        name: golang
      when: configure_golang
      tags:
        - golang

    - name: Configure npm
      ansible.builtin.import_role:
        name: npm
      when: configure_npm
      tags:
        - npm

    - name: Configure pip
      ansible.builtin.import_role:
        name: pip
      when: configure_pip
      tags:
        - pip

    - name: Configure rust
      ansible.builtin.import_role:
        name: rust
      when: configure_rust
      tags:
        - rust

    - name: Configure haskell
      ansible.builtin.import_role:
        name: haskell
      when: configure_haskell
      tags:
        - haskell

    - name: Configure fzf
      ansible.builtin.import_role:
        name: fzf
      when: configure_fzf
      tags:
        - fzf

    - name: Configure kitty
      ansible.builtin.import_role:
        name: kitty
      when: configure_kitty
      tags:
        - kitty

    - name: Configure vifm
      ansible.builtin.import_role:
        name: vifm
      when: configure_vifm
      tags:
        - vifm

    - name: Configure vim
      ansible.builtin.import_role:
        name: vim
      when: configure_vim
      tags:
        - vim

    - name: Configure fd
      ansible.builtin.import_role:
        name: fd
      when: configure_fd
      tags:
        - fd

    - name: Configure rg
      ansible.builtin.import_role:
        name: rg
      when: configure_rg
      tags:
        - rg

    - name: Configure memo
      ansible.builtin.import_role:
        name: memo
      when: configure_memo
      tags:
        - memo

    - name: Configure lsp's
      ansible.builtin.import_role:
        name: lsp
      when: configure_lsp
      tags:
        - lsp

    - name: Configure neovim
      ansible.builtin.import_role:
        name: neovim
      when: configure_neovim
      tags:
        - neovim

    - name: Configure bat
      ansible.builtin.import_role:
        name: bat
      when: configure_bat
      tags:
        - bat

    - name: Configure ag
      ansible.builtin.import_role:
        name: ag
      when: configure_ag
      tags:
        - ag

    - name: Configure tmux
      ansible.builtin.import_role:
        name: tmux
      when: configure_tmux
      tags:
        - tmux

    - name: Configure libpq
      ansible.builtin.import_role:
        name: libpq
      when: configure_libpq
      tags:
        - libpq

    - name: Configure secrets
      ansible.builtin.import_role:
        name: secrets
      when: configure_secrets
      tags:
        - secrets

    - name: Configure gnupg
      ansible.builtin.import_role:
        name: gnupg
      when: configure_gnupg
      tags:
        - gnupg

    - name: Configure ssh
      ansible.builtin.import_role:
        name: ssh
      when: configure_ssh
      tags:
        - ssh

    - name: Configure neomutt
      ansible.builtin.import_role:
        name: neomutt
      when: configure_neomutt
      tags:
        - neomutt

    - name: Configure calibre
      ansible.builtin.import_role:
        name: calibre
      when: configure_calibre
      tags:
        - calibre

    - name: Configure fonts
      ansible.builtin.import_role:
        name: fonts
      when: configure_fonts
      tags:
        - fonts

    - name: Configure aws
      ansible.builtin.import_role:
        name: aws
      when: configure_aws
      tags:
        - aws

    - name: Configure azure cli
      ansible.builtin.import_role:
        name: azure_cli
      when: configure_azure_cli
      tags:
        - azure_cli

    - name: Configure terraform
      ansible.builtin.import_role:
        name: terraform
      when: configure_terraform
      tags:
        - terraform

    - name: Configure firefox
      ansible.builtin.import_role:
        name: firefox
      when: configure_firefox
      tags:
        - firefox

    - name: Configure discord
      ansible.builtin.import_role:
        name: discord
      when: configure_discord
      tags:
        - discord

    - name: Configure spotify
      ansible.builtin.import_role:
        name: spotify
      when: configure_spotify
      tags:
        - spotify

    - name: Configure flatpak
      ansible.builtin.import_role:
        name: flatpak
      when: configure_flatpak
      tags:
        - flatpak

    - name: Configure synology drive
      ansible.builtin.import_role:
        name: synology_drive
      when: configure_synology_drive
      tags:
        - synology_drive

    - name: Configure rofi
      ansible.builtin.import_role:
        name: rofi
      when: configure_rofi
      tags:
        - rofi

    - name: Configure i3
      ansible.builtin.import_role:
        name: i3
      when: configure_i3
      tags:
        - i3

    - name: Configure virt manager
      ansible.builtin.import_role:
        name: virt_manager
      when: configure_virt_manager
      tags:
        - virt_manager

    - name: Configure systemd_resolved
      ansible.builtin.import_role:
        name: systemd_resolved
      when: configure_systemd_resolved
      tags:
        - systemd_resolved
