---
- name: Configure apt sources.list with contrib, non-free, non-free-firmware, and backports
  become: true
  when: ansible_facts.distribution == 'Debian'
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"
  tags:
    - install

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  tags:
    - install

- name: Install packages with apt
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  become: true
  tags:
    - install

- name: Update and upgrade installed apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    autoremove: true
    autoclean: true
  tags:
    - update
