- name: Install packages with apt
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
  tags:
    - install

- name: Update and upgrade installed apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  tags:
    - update
