- name: Install software-properties-common with apt
  ansible.builtin.apt:
    name: software-properties-common
    state: present
  become: true
  tags:
    - install

- name: Ensure contrib, non-free & non-free-firmware repositories are added
  become: true
  ansible.builtin.command: apt-add-repository -yn contrib non-free non-free-firmware
  tags:
    - install

- name: Ensure backports repository is enabled
  become: true
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list
    block: |
      # backports
      deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free-firmware non-free

- name: Install packages with apt
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  become: true
  tags:
    - install

- name: Update and upgrade installed apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  tags:
    - update
