- name: Install packages with homebrew
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  tags:
    - install

- name: Update packages installed with homebrew
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - update
