---
galaxy_info:
  role_name: haskell
  author: ldonnez
  description: Install ghcup toolchain
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: dotfiles
  - role: packages
