---
galaxy_info:
  role_name: asdf
  author: ldonnez
  description: Manage multiple runtime versions with a single CLI tool
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: dotfiles
