---
galaxy_info:
  role_name: fd
  author: ldonnez
  description: A simple, fast and user-friendly alternative to 'find'
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: dotfiles
