---
galaxy_info:
  role_name: npm
  author: ldonnez
  description: Node package manager
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: asdf
