---
- name: Check if pipx is already bootstrapped in ~/.local/bin
  when: ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'
  ansible.builtin.stat:
    path: "{{ ansible_facts.user_dir }}/.local/bin/pipx"
  register: pip_pipx_bin
  tags:
    - install

- name: Install pipx
  when:
    - ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu'
    - not pip_pipx_bin.stat.exists
  tags:
    - install
  block:
    - name: Install python3-setuptools, pipx with apt
      ansible.builtin.apt:
        name: ["python3-setuptools", "pipx"]
        state: present
      become: true

    - name: Bootstrap current pipx into ~/.local/bin
      ansible.builtin.command: pipx install pipx
      args:
        creates: "{{ ansible_facts.user_dir }}/.local/bin/pipx"

    - name: Remove outdated apt pipx
      ansible.builtin.apt:
        name: pipx
        state: absent
      become: true

- name: Install python3 with hombrew
  community.general.homebrew:
    name: ["python3"]
    state: present
  when: ansible_facts.os_family == "Darwin"
  tags:
    - install

- name: Install pipx with homebrew
  community.general.homebrew:
    name: ["pipx"]
    state: present
  when: ansible_facts.os_family == "Darwin"
  tags:
    - install

- name: Getting pipx binary location
  ansible.builtin.command: which pipx
  register: pip_pipx_binary
  changed_when: false
  environment:
    PATH: "{{ ansible_facts.user_dir }}/.local/bin:{{ ansible_facts.env.PATH }}"
  tags:
    - update
    - install

- name: Install packages with pipx
  community.general.pipx:
    name: "{{ item }}"
    executable: "{{ pip_pipx_binary.stdout }}"
  loop: "{{ pip_packages }}"
  when: pip_packages is defined
  tags:
    - install

- name: Upgrade packages with pipx
  community.general.pipx:
    state: upgrade_all
    executable: "{{ pip_pipx_binary.stdout }}"
  tags:
    - update
