---
- name: Install docker desktop with apt
  when: ansible_facts.os_family == "Debian"
  become: true
  tags:
    - install
  block:
    - name: Install python3-debian (required by deb822_repository)
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Add docker to sources list
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_facts.distribution_release }}"
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Install docker packages
      ansible.builtin.apt:
        name: "docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin"
        state: present
        update_cache: true

    - name: Download & install docker-desktop .deb package
      ansible.builtin.apt:
        deb: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64
      register: docker_desktop_result
      failed_when: >
        docker_desktop_result.failed and
        ('A later version is already installed' not in docker_desktop_result.msg)
      tags:
        - update
