---
galaxy_info:
  role_name: vifm
  author: ldonnez
  description: Vifm is a file manager with curses interface.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: dotfiles
