---
- name: Start ssh-agent on login
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.user_dir }}/.zprofile"
    block: |
      if [ ! -S ~/.ssh/ssh_auth_sock ]; then
        eval `ssh-agent`
        ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
      fi
      export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
    create: true
    mode: "0700"
  tags:
    - install

- name: Ensure .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.ssh"
    state: directory
    mode: "0700"
  tags:
    - install

- name: Copy SSH private key from secrets repo
  ansible.builtin.copy:
    src: "{{ ansible_facts.user_dir }}/.secrets/.ssh/id_rsa"
    dest: "{{ ansible_facts.user_dir }}/.ssh/id_rsa"
    mode: "0600"
    decrypt: true
  tags:
    - install

- name: Copy SSH public key from secrets repo
  ansible.builtin.copy:
    src: "{{ ansible_facts.user_dir }}/.secrets/.ssh/id_rsa.pub"
    dest: "{{ ansible_facts.user_dir }}/.ssh/id_rsa.pub"
    mode: "0644"
    decrypt: false
  tags:
    - install

- name: Copy SSH config from secrets repo
  ansible.builtin.copy:
    src: "{{ ansible_facts.user_dir }}/.secrets/.ssh/config"
    dest: "{{ ansible_facts.user_dir }}/.ssh/config"
    mode: "0600"
    decrypt: true
  tags:
    - install

- name: Generate root key
  become: true
  ansible.builtin.command: ssh-keygen -A
  args:
    creates: /etc/ssh/ssh_host_rsa_key
  tags:
    - install
