- name: Include install
  ansible.builtin.import_tasks: install.yml
  when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"

- name: Include plugins
  ansible.builtin.import_tasks: plugins.yml
  when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"

- name: Include configure
  ansible.builtin.import_tasks: configure.yml
  when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"
