- name: Install & Configure asdf plugins
  when: asdf_plugins|length > 0
  tags:
    - install

  block:
    - name: Install apt depedencies for plugins
      ansible.builtin.apt:
        name: "{{ item.apt_dependencies }}"
        state: present
      when: ansible_os_family == 'Debian'
      become: true
      loop: "{{ asdf_plugins }}"

    - name: Install homebrew depedencies for plugins
      community.general.homebrew:
        name: "{{ item.homebrew_dependencies }}"
        state: present
      when: ansible_os_family == 'Darwin'
      loop: "{{ asdf_plugins }}"

    - name: Install asdf plugins
      ansible.builtin.command: "asdf plugin-add {{ item.name }} {{ item.repository }}"
      register: asdf_plugin_add_output
      failed_when: asdf_plugin_add_output.rc == 1
      loop: "{{ asdf_plugins }}"

    - name: Install software versions
      ansible.builtin.command: "asdf install {{ item.0.name }} {{ item.1 }}"
      with_subelements:
        - "{{ asdf_plugins }}"
        - versions
        - flags:
            skip_missing: true

    - name: Set global software versions
      ansible.builtin.command: "asdf global {{ item.name }} {{ item.global }}"
      when: item.global is defined
      loop: "{{ asdf_plugins }}"

- name: Update asdf plugins
  ansible.builtin.command: asdf plugin update --all
  tags:
    - update
