---
- name: Check if spotify is installed
  ansible.builtin.stat:
    path: /usr/bin/spotify
  register: spotify_bin
  tags:
    - install

- name: Install Spotify client with apt
  when:
    - ansible_facts.os_family == "Debian"
    - not spotify_bin.stat.exists
  become: true
  tags:
    - install
  block:
    - name: Install python3-debian (required by deb822_repository)
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Add spotify to sources list
      ansible.builtin.deb822_repository:
        name: spotify
        types: deb
        uris: https://repository.spotify.com
        suites: stable
        components: non-free
        signed_by: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc
        state: present

    - name: Install Spotify client package
      ansible.builtin.apt:
        name: "spotify-client"
        state: present
        update_cache: true
