- name: "Ensure kitty config dir"
  ansible.builtin.file:
    path: "{{ kitty_config_dir }}"
    state: directory
    recurse: true
  tags:
    - install

- name: Symlink kitty.conf
  ansible.builtin.file:
    src: "{{ kitty_dotfiles_path }}/kitty.conf"
    dest: "{{ kitty_config_dir }}/kitty.conf"
    state: link
  tags:
    - install
