---
galaxy_info:
  role_name: steam
  author: ldonnez
  description: Install steam
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: packages
  - role: nvidia
