---
galaxy_info:
  role_name: ssh
  author: ldonnez
  description: SSH is a software package that enables secure system administration and file transfers over insecure networks.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: secrets
