- name: Install kitty with curl
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  tags:
    - kitty

- name: Symlink ~/.kitty.yml from source {{ dotfiles_directory_path }}/.kitty.yml
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/kitty/kitty.conf", dest: "~/.config/kitty/kitty.conf" }
  tags:
    - kitty
