- name: Install tmux with homebrew
  homebrew: name=tmux state=present
  tags:
    - tmux

- name: Install Tmux Plugin Manager with git
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - tmux

- name: Symlink ~/.tmux.conf from source {{ dotfiles_directory_path }}/.tmux.conf
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.tmux.conf", dest: "~/.tmux.conf" }
  tags:
    - tmux

- name: Install tmux plugins
  shell: ~/.tmux/plugins/tpm/bin/install_plugins
  tags:
    - tmux
