- name: Install asdf
  git: repo='https://github.com/asdf-vm/asdf.git' dest=~/.asdf version="v0.8.1" force=yes
  tags:
    - asdf

- name: Install nodejs asdf plugin
  ignore_errors: yes
  shell: ~/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  tags:
    - asdf

- name: Install ruby asdf plugin
  ignore_errors: yes
  shell: ~/.asdf/bin/asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  tags:
    - asdf

- name: Install python asdf plugin
  ignore_errors: yes
  shell: ~/.asdf/bin/asdf plugin add python
  tags:
    - asdf

- name: Install latest nodejs
  shell: ~/.asdf/bin/asdf install nodejs latest
  tags:
    - asdf

- name: set latest nodejs global
  shell: ~/.asdf/bin/asdf global nodejs latest
  tags:
    - asdf

- name: install latest ruby
  shell: ~/.asdf/bin/asdf install ruby latest
  tags:
    - asdf

- name: set latest ruby global
  shell: ~/.asdf/bin/asdf global ruby latest
  tags:
    - asdf

- name: install latest python3
  shell: ~/.asdf/bin/asdf install python latest
  tags:
    - asdf

- name: install latest python2
  shell: ~/.asdf/bin/asdf install python 2.7.18
  tags:
    - asdf

- name: set latest python2 & python3 global
  shell: ~/.asdf/bin/asdf global python latest 2.7.18
  tags:
    - asdf

- name: Install yarn
  npm:  name=yarn global=yes
  tags:
    - asdf

- name: Set yarn bin to ~/.yarn
  shell: yarn config set prefix ~/.yarn
  tags:
    - asdf

- name: Set npm bin to ~/.npm
  shell: npm config set prefix ~/.npm
  tags:
    - asdf

- name: Symlink ~/.asdfrc from source {{ dotfiles_directory_path }}/.asdfrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.asdfrc", dest: "~/.asdfrc" }
  tags:
    - asdf

- name: Update asdf
  shell: ~/.asdf/bin/asdf update
  tags:
    - update

- name: Update asdf plugins
  shell: ~/.asdf/bin/asdf plugin update --all
  tags:
    - update

- name: Update global npm packages
  shell: npm update -g
  tags:
    - update

- name: Update global yarn packages
  shell: yarn global upgrade
  tags:
    - update

- name: Update global gems
  become_user: lenny
  command: zsh -lc "gem update"
  tags:
    - update

- name: Upgrade pip2 && pip3
  shell: pip2 install --upgrade pip && pip3 install --upgrade pip
  tags:
    - update
