- name: Symlink ~/.zshrc from source {{ dotfiles_directory_path }}/.zshrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.zshrc", dest: "~/.zshrc" }
  tags:
    - zsh

- name: Don't show last login message when opening a terminal
  file:
    path: "~/.hushlogin"
    state: touch
  tags:
    - zsh

- name: Set maxfiles limit to a higher value
  shell: sudo launchctl limit maxfiles 10240 unlimited
  become: yes
  tags:
    - zsh
