- name: Install Postgresql
  homebrew: name=postgresql state=present
  tags:
    - postgresql

- name: Starting postgresql...
  command: brew services start postgresql
  tags:
    - postgresql

- name: Symlink ~/.psqlrc from source {{ dotfiles_directory_path }}/.psqlrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.psqlrc", dest: "~/.psqlrc" }
  tags:
    - postgresql
