- name: Symlink ~/.zshrc from source {{ dotfiles_directory_path }}/.zshrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.zshrc", dest: "~/.zshrc" }
  tags:
    - zsh

- name: Don't show last login message when opening a terminal
  file:
    path: "~/.hushlogin"
    state: touch
  tags:
    - zsh

- name: Set maxfiles limit to a higher value
  shell: sudo launchctl limit maxfiles 10240 unlimited
  become: true
  tags:
    - zsh

- name: Update zsh-z plugin
  git: repo='https://github.com/agkozak/zsh-z' dest=~/.zsh/plugins/zsh-z version="master" update=yes
  tags:
    - update

- name: Update fzf-tab plugin
  git: repo='https://github.com/Aloxaf/fzf-tab' dest=~/.zsh/plugins/fzf-tab version="master" update=yes
  tags:
    - update
