- name: Check if {{ dotfiles_directory_path }} already exists
  stat:
      path: "{{ dotfiles_directory_path }}"
  register: dotfiles_directory
  tags:
    - dotfiles

- name: Clone dotfiles into {{ dotfiles_directory_path  }} if not exists
  when: dotfiles_directory.stat.exists == false
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_directory_path }}"
  tags:
    - dotfiles
