- include: install_extra_packages_with_homebrew.yml
- include: configure_git.yml
- include: configure_bat.yml
- include: configure_zsh.yml
- include: configure_asdf.yml
- include: configure_vim.yml
- include: configure_vifm.yml
- include: configure_alacritty.yml
- include: configure_kitty.yml
- include: configure_tmux.yml
- include: configure_ag.yml
- include: configure_fd.yml
- include: configure_rg.yml
- include: configure_ssh.yml
- include: configure_libpq.yml
- include: configure_gnugpg.yml
- include: configure_secrets.yml
- include: configure_mutt.yml
