---
- name: Check if Azure CLI is installed
  ansible.builtin.stat:
    path: /usr/bin/az
  register: azure_cli_bin
  tags:
    - install

- name: Install Azure CLI with apt
  when:
    - ansible_facts.os_family == "Debian"
    - not azure_cli_bin.stat.exists
  become: true
  tags:
    - install
  block:
    - name: Install python3-debian (required by deb822_repository)
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Get system architecture (e.g. amd64)
      ansible.builtin.command: dpkg --print-architecture
      register: azure_cli_system_arch
      changed_when: false

    - name: Remove legacy microsoft keyring
      ansible.builtin.file:
        path: /etc/apt/keyrings/microsoft.gpg
        state: absent

    - name: Add azure cli to sources list
      ansible.builtin.deb822_repository:
        name: azure-cli
        types: deb
        uris: https://packages.microsoft.com/repos/azure-cli/
        suites: "{{ ansible_facts.lsb.codename }}"
        components: main
        architectures: "{{ azure_cli_system_arch.stdout }}"
        signed_by: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Install Azure CLI package
      ansible.builtin.apt:
        name: "azure-cli"
        state: present
        update_cache: true
