---
- name: Tap homebrew repositories
  when: ansible_facts.os_family == "Darwin"
  community.general.homebrew_tap:
    name: "hashicorp/tap"
    state: present
  tags:
    - install

- name: Install terraform with homebrew
  when: ansible_facts.os_family == "Darwin"
  community.general.homebrew:
    name: "hashicorp/tap/terraform"
    state: present
  tags:
    - install

- name: Check if terraform is installed
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.stat:
    path: /usr/bin/terraform
  register: terraform_bin
  tags:
    - install

- name: Install terraform with apt
  when:
    - ansible_facts.os_family == "Debian"
    - not terraform_bin.stat.exists
  become: true
  tags:
    - install
  block:
    - name: Get hashicorp signing key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp.asc
        mode: "0644"

    - name: Convert key to GPG format
      ansible.builtin.shell: gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg /tmp/hashicorp.asc
      args:
        executable: /bin/bash
        creates: /etc/apt/keyrings/hashicorp.gpg

    - name: Get system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: terraform_system_arch
      changed_when: false

    - name: Create hashicorp sources file
      ansible.builtin.copy:
        mode: "0644"
        content: |
          Types: deb
          URIs: https://apt.releases.hashicorp.com
          Suites: {{ ansible_facts.lsb.codename }}
          Components: main
          Architectures: {{ terraform_system_arch.stdout }}
          Signed-by: /etc/apt/keyrings/hashicorp.gpg
        dest: /etc/apt/sources.list.d/hashicorp.sources

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install terraform with apt
      ansible.builtin.apt:
        name: terraform
        state: present

    - name: Install terraform-ls with apt
      ansible.builtin.apt:
        name: terraform-ls
        state: present

  always:
    - name: Cleanup /tmp/hashicorp.asc
      ansible.builtin.file:
        path: /tmp/hashicorp.asc
        state: absent
