---
galaxy_info:
  role_name: lsp
  author: ldonnez
  description: Language server protocol
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: npm
  - role: yarn
  - role: pip
  - role: rust
