---
galaxy_info:
  role_name: git
  author: ldonnez
  description: Git - fast, scalable, distributed revision control system
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: dotfiles
