---
galaxy_info:
  role_name: secrets
  author: ldonnez
  description: Synchronize secrets locally (.gnupg, ssh,...)
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies:
  - role: github_cli # Necessary to authenticate to clone the secrets repository
  - role: gnome_keyring # Ensures gpg key passwords are cached securely.
