---
galaxy_info:
  role_name: secrets
  author: ldonnez
  description: Synchronize secrets locally (.gnupg, ssh,...)
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
