---
galaxy_info:
  role_name: yarn
  author: ldonnez
  description: Yarn is a package manager that doubles down as project manager.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies:
  - role: asdf
