- name: Install zsh with apt
  become: yes
  apt: name=zsh state=present
  tags:
    - zsh

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - zsh

- name: Symlink ~/.zshrc from source {{ dotfiles_directory_path }}/.zshrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.zshrc", dest: "~/.zshrc" }
  tags:
    - zsh

- name: Symlink ~/.wslrc from source {{ dotfiles_directory_path }}/.wslrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.wslrc", dest: "~/.wslrc" }
  tags:
    - zsh

- name: Remove existing ~/.zsh
  file: path=~/.zsh state=absent
  tags:
    - zsh

- name: Clone zsh-z into ~/.zsh/plugins
  git:
    repo: "https://github.com/agkozak/zsh-z"
    dest: "~/.zsh/plugins/zsh-z"
  tags:
    - zsh

- name: Clone fzf-tab into ~/.zsh/plugins
  git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "~/.zsh/plugins/fzf-tab"
  tags:
    - zsh

- name: Don't show last login message when opening a terminal
  file:
    path: "~/.hushlogin"
    state: touch
  tags:
    - zsh
