- name: Install vifm with apt
  become: true
  apt: name=vifm state=present
  tags:
    - vifm

- name: Create ~/.config/vifm directory if not exists
  file: path=~/.config/vifm state=directory recurse=yes
  tags:
    - vifm

- name: Symlink ~/.config/vifm/vifm from source {{ dotfiles_directory_path }}/vifmrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/vifm/vifmrc", dest: "~/.config/vifm/vifmrc" }
  tags:
    - vifm
