- name: Synchronization ~/private
  ansible.posix.synchronize:
    src: "{{ private_dotfiles_source}}/"
    dest: "{{ private_dotfiles_path }}/"
    recursive: true
    delete: true
    checksum: true
  tags:
    - secrets

- name: Symlink ~/.secrets directory from source {{ private_dotfiles_path }}/.secrets
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ private_dotfiles_path }}/.secrets", dest: "~/.secrets" }
  tags:
    - secrets

- name: Give correct access righs to ~/.secrets
  file: path="~/.secrets" mode="0700"
  become_user: root
  tags:
    - secrets
