- name: Install asdf
  git: repo='https://github.com/asdf-vm/asdf.git' dest=~/.asdf version="v0.8.1" force=yes
  tags:
    - asdf

- name: Install nodejs asdf plugin
  ignore_errors: true
  shell: . ~/.asdf/asdf.sh && asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Install ruby dependencies
  become: true
  apt: name={{ item }} state=present
  loop:
    - libssl-dev
  tags:
    - asdf

- name: Install ruby asdf plugin
  ignore_errors: true
  shell: . ~/.asdf/asdf.sh && asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Install latest nodejs
  shell: . ~/.asdf/asdf.sh && asdf install nodejs latest
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: set latest nodejs global
  shell: . ~/.asdf/asdf.sh && asdf global nodejs latest
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: install latest ruby
  shell: . ~/.asdf/asdf.sh && asdf install ruby latest
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: set latest ruby global
  shell: . ~/.asdf/asdf.sh && asdf global ruby latest
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Set npm bin to ~/.npm
  shell: . ~/.asdf/asdf.sh && npm config set prefix ~/.npm
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Install yarn
  shell: . ~/.asdf/asdf.sh && npm install yarn -g
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Set yarn bin to ~/.yarn
  shell: . ~/.asdf/asdf.sh && asdf reshim && ~/.npm/bin/yarn config set prefix ~/.yarn
  args:
    executable: /bin/bash
  tags:
    - asdf

- name: Symlink ~/.asdfrc from source {{ dotfiles_directory_path }}/.asdfrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.asdfrc", dest: "~/.asdfrc" }
  tags:
    - asdf

- name: Update asdf
  command: ~/.asdf/bin/asdf update
  tags:
    - update

- name: Update asdf plugins
  command: ~/.asdf/bin/asdf plugin update --all
  tags:
    - update

- name: Update global npm packages
  shell: . ~/.asdf/asdf.sh && npm update -g
  args:
    executable: /bin/bash
  tags:
    - update

- name: Update global yarn packages
  shell: . ~/.asdf/asdf.sh && asdf reshim && ~/.npm/bin/yarn global upgrade
  args:
    executable: /bin/bash
  tags:
    - update

- name: Update global gems
  become_user: lenny
  shell: . ~/.asdf/asdf.sh && gem update
  args:
    executable: /bin/bash
  tags:
    - update

- name: Upgrade pip3
  command: pip3 install --upgrade pip
  tags:
    - update
