- name: Install fzf with git
  git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: ~/.fzf
  tags:
    - fzf

- name: Update fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    update: yes
  tags:
    - update
    - update-fzf

- name: Install fzf
  shell: ~/.fzf/install
  tags:
    - fzf
    - update
    - update-fzf

