- name: Install zsh with apt
  become: true
  apt: name=zsh state=present
  tags:
    - zsh

- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - zsh

- name: Symlink ~/.zshrc from source {{ dotfiles_directory_path }}/.zshrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.zshrc", dest: "~/.zshrc" }
  tags:
    - zsh

- name: Symlink ~/.wslrc from source {{ dotfiles_directory_path }}/.wslrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.wslrc", dest: "~/.wslrc" }
  tags:
    - zsh

- name: Remove existing ~/.zsh
  file: path=~/.zsh state=absent
  tags:
    - zsh

- name: Don't show last login message when opening a terminal
  file:
    path: "~/.hushlogin"
    state: touch
  tags:
    - zsh

- name: Update zsh-z plugin
  git: repo='https://github.com/agkozak/zsh-z' dest=~/.zsh/plugins/zsh-z version="master" update=yes
  tags:
    - update

- name: Update fzf-tab plugin
  git: repo='https://github.com/Aloxaf/fzf-tab' dest=~/.zsh/plugins/fzf-tab version="master" update=yes
  tags:
    - update
