- name: "Ensure {{ fd_config_dir }}"
  ansible.builtin.file:
    name: "{{ fd_config_dir }}"
    state: directory
    recurse: true
  tags:
    - install

- name: Symlink .ignore
  ansible.builtin.file:
    src: "{{ dotfiles_directory_path }}/.agignore"
    dest: "{{ fd_config_dir }}/ignore"
    state: link
  tags:
    - install

- name: Link fdfind -> fd
  when: ansible_os_family == "Debian"
  tags:
    - install

  block:
    - name: Getting fdfind binary location
      ansible.builtin.command: which fdfind
      register: fd_fdfind_binary

    - name: Link with fdfind binary location
      ansible.builtin.file:
        src: "{{ fd_fdfind_binary.stdout }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/fd"
        state: link
        force: true
      when: ansible_os_family == "Debian"
      tags:
        - install
