- name: Symlink nvim config
  ansible.builtin.file:
    src: "{{ neovim_dotfiles_path }}"
    dest: "{{ neovim_config_dir }}"
    state: link
  tags:
    - install

- name: Install neovim npm package globally
  community.general.npm:
    name: neovim
    global: true
  environment:
    PATH: "{{ ansible_facts.user_dir }}/.local/share/mise/shims:{{ ansible_facts.user_dir }}/.local/bin:{{ ansible_facts.env.PATH }}"
  tags:
    - install

- name: Install neovim plugins from nvim-pack-lock.json file
  ansible.builtin.command: nvim --headless "+lua vim.pack.update(nil, { target = "lockfile" })" +qa
  tags:
    - install

- name: Update neovim plugins
  ansible.builtin.command: nvim --headless "+lua vim.pack.update(nil, { force = true })" +qa
  tags:
    - update
