- name: Install neovim
  when: ansible_os_family == "Debian"
  become: true
  tags:
    - install
  block:
    - name: Install build dependencies
      ansible.builtin.apt:
        name:
          [
            "ninja-build",
            "gettext",
            "cmake",
            "unzip",
            "curl",
            "build-essential"
          ]
        state: present

    - name: Git clone neovim repository
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        depth: 1
        version: stable
        dest: /tmp/neovim

    - name: Configure neovim build
      ansible.builtin.command: make CMAKE_BUILD_TYPE=RelWithDebInfo
      args:
        chdir: /tmp/neovim

    - name: Create nvim-linux-x86_64.deb package
      ansible.builtin.command: cpack -G DEB
      args:
        chdir: /tmp/neovim/build

    - name: Install nvim-linux-x86_64.deb package
      ansible.builtin.command: dpkg -i --force-overwrite nvim-linux-x86_64.deb
      args:
        chdir: /tmp/neovim/build

    - name: Remove /tmp/neovim
      ansible.builtin.file:
        path: /tmp/neovim
        state: absent

- name: Install neovim & neovim-qt with homebrew
  community.general.homebrew:
    name: ["neovim", "neovim-qt"]
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - install
