---
galaxy_info:
  role_name: synchronize
  author: ldonnez
  description: Sync directories & files
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
