name: Setup WSL ubuntu-24.04

on:
  workflow_dispatch:

jobs:
  setup_wsl_ubuntu:
    name: setup_wsl_ubuntu
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Run make setup-wsl-ubuntu
        run: make setup-wsl-ubuntu
