---
galaxy_info:
  role_name: pip
  author: ldonnez
  description: Package installer for Python
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
